# Generated by Django 3.2 on 2023-04-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(default=1, help_text='Currency of the wallet', on_delete=django.db.models.deletion.CASCADE, to='api.currency', verbose_name='Currency'),
            preserve_default=False,
        ),
    ]
