apiVersion: v1
kind: ConfigMap
metadata:
  name: django-moneybox-configmap
  namespace: moneybox
data:
  ENV: "dev"
  DJANGO_DEBUG: "True"
  CELERY_BEAT_SCHEDULER: "django_celery_beat.schedulers:DatabaseScheduler"
