apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-moneybox
  namespace: moneybox
  labels:
    app: django-moneybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-moneybox
  template:
    metadata:
      labels:
        app: django-moneybox
    spec:
      initContainers:
        - name: migrations
          image: error0x001/moneybox_backend:latest
          imagePullPolicy: Always
          command:
            - python
            - manage.py
            - migrate
            - --noinput
          envFrom:
            - configMapRef:
                name: django-moneybox-configmap
            - secretRef:
                name: django-moneybox-secret
        - name: collectstatic
          image: error0x001/moneybox_backend:latest
          command:
            - python
            - manage.py
            - collectstatic
            - --noinput
          volumeMounts:
            - name: django-moneybox-static-volume
              mountPath: /app/static
      containers:
      - name: django-moneybox
        image: error0x001/moneybox_backend:latest
        imagePullPolicy: Always
        ports:
          - name: default
            containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthcheck/
            port: default
            scheme: HTTP
          timeoutSeconds:
            10
          periodSeconds:
            100
        envFrom:
          - configMapRef:
              name: django-moneybox-configmap
          - secretRef:
              name: django-moneybox-secret
        volumeMounts:
          - name: django-moneybox-static-volume
            mountPath: /app/static
        command:
          - gunicorn
          - moneybox.wsgi:application
          - --bind
          - 0.0.0.0:8000
      - name: django-moneybox-celery-beat
        image: error0x001/moneybox_backend:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: django-moneybox-configmap
          - secretRef:
              name: django-moneybox-secret
        command:
          - celery
          - -A
          - moneybox
          - beat
          - -l
          - info
      - name: django-moneybox-celery-worker
        image: error0x001/moneybox_backend:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: django-moneybox-configmap
          - secretRef:
              name: django-moneybox-secret
        command:
          - celery
          - -A
          - moneybox
          - worker
          - -l
          - info
      volumes:
        - name: django-moneybox-static-volume
          emptyDir: { }
