# Generated by Django 3.2 on 2023-08-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='The unique code for this currency', max_length=3, unique=True, verbose_name='Currency Code'),
        ),
    ]
