# Generated by Django 3.2 on 2023-09-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='nominal',
            field=models.CharField(default='', help_text='Currency denomination for exchange rate conversion', max_length=15, verbose_name='Currency Nominal for rates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='value',
            field=models.CharField(default='', help_text='Currency value for exchange rate"', max_length=15, verbose_name='Currency exchange rate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='The name of the currency, e.g. US Dollar', max_length=255, verbose_name='Currency Name'),
        ),
    ]
