# Generated by Django 3.2 on 2023-09-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_create_rouble_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='The unique code for this currency', max_length=3, unique=True, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='The name of the currency, e.g. US Dollar', max_length=255, verbose_name='Currency Name'),
        ),
    ]
