# Generated by Django 3.2 on 2023-09-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_create_rouble_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='cbr_valute_id',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='nominal',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='value',
        ),
    ]
