# Generated by Django 3.2 on 2023-09-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230917_0657'),
        ('wallet', '0003_auto_20230906_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'get_latest_by': ('created_at',), 'verbose_name': 'Currency rate', 'verbose_name_plural': 'Currency rates'},
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='source_currency',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='target_currency',
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='currency',
            field=models.ForeignKey(default=0, help_text='Currency', on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='wallet.currency', verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(db_index=True, help_text='Members of the group', null=True, related_name='groups', to='users.APIUser', verbose_name='Group members'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time of creation', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time of last update', verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('invite_code', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='wallet.group')),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
            },
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(fields=('invite_code', 'group'), name='unique_invite'),
        ),
    ]
