# Generated by Django 3.2 on 2023-09-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_apiuser_invite'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wallet', '0003_auto_20230906_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ForeignKey(default=1, help_text='Members of the group', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.apiuser', verbose_name='Group members'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time of creation', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Date and time of last update', verbose_name='Updated at')),
                ('invite_code', models.CharField(max_length=7, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Timestamp Mixin',
                'verbose_name_plural': 'Timestamp Mixins',
                'abstract': False,
            },
        ),
    ]
