# Generated by Django 3.2 on 2023-09-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_apiuser_invite'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wallet', '0006_auto_20230917_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ForeignKey(help_text='Members of the group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.apiuser', verbose_name='Group members'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_code',
            field=models.CharField(max_length=7),
        ),
    ]
