# Generated by Django 3.2 on 2023-09-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20230929_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=5, help_text='The rate at which the source currencycan be exchanged for the target currency.', max_digits=12, verbose_name='Exchange Rate'),
        ),
    ]
