# Generated by Django 3.2 on 2023-09-18 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_apiuser_invite'),
        ('wallet', '0008_auto_20230918_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ForeignKey(help_text='Members of the group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.apiuser', verbose_name='Group members'),
        ),
    ]
