# Generated by Django 3.2 on 2023-10-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_currencyrate_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.RemoveField(
            model_name='income',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='incomecategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='created_by',
        ),
    ]
