# Generated by Django 3.2 on 2023-10-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_api_user"),
        ("wallet", "0009_auto_20231002_1924"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.apiuser",
                verbose_name="User who made the expense",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who created this expense category",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.apiuser",
                verbose_name="Created by",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                db_index=True,
                help_text="Members of the group",
                related_name="groups",
                to="users.APIUser",
                verbose_name="Group members",
            ),
        ),
        migrations.AddField(
            model_name="income",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.apiuser", verbose_name="Income creator"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incomecategory",
            name="created_by",
            field=models.ForeignKey(
                help_text="Profile that created the income category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="income_categories",
                to="users.apiuser",
                verbose_name="Created by",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transfer",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who made the transfer.",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.apiuser",
                verbose_name="Created by",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="created_by",
            field=models.ForeignKey(
                help_text="Owner of the wallet",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.apiuser",
                verbose_name="Created by",
            ),
            preserve_default=False,
        ),
    ]
