# Generated by Django 3.2 on 2023-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_apiuser_invite'),
        ('wallet', '0004_auto_20230917_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(db_index=True, help_text='Members of the group', null=True, related_name='groups', to='users.APIUser', verbose_name='Group members'),
        ),
    ]
