# Generated by Django 3.2 on 2023-09-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20230918_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='wallet.group'),
        ),
    ]
