# Generated by Django 3.2 on 2023-09-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_invite_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_code',
            field=models.IntegerField(),
        ),
    ]
