# Generated by Django 3.2 on 2023-09-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'administrator', 'verbose_name_plural': 'administrators'},
        ),
        migrations.AlterField(
            model_name='user',
            name='api_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='users.apiuser'),
        ),
    ]
