# Generated by Django 3.2 on 2023-09-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230915_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={'verbose_name': 'API User', 'verbose_name_plural': 'API Users'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Administrator', 'verbose_name_plural': 'Administrators'},
        ),
    ]
