# Generated by Django 3.2 on 2023-09-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230917_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='invite',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
