# Generated by Django 3.2 on 2023-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230917_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
