# Generated by Django 3.2 on 2023-09-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_apiuser_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='invite',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='invite_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
