# Generated by Django 3.2 on 2023-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_apiuser_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="api_user",
        ),
        migrations.AlterField(
            model_name="apiuser",
            name="token",
            field=models.BinaryField(),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
            preserve_default=False,
        ),
    ]
