# Generated by Django 3.2 on 2023-09-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230919_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='invite_code',
        ),
    ]
