# Generated by Django 3.2 on 2023-10-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_auto_20231002_1924"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="admin_user", to="users.apiuser"
            ),
            preserve_default=False,
        ),
    ]
